platform :ios,'7.1'
pod 'AFNetworking', '~> 2.6.3'
pod 'SocketRocket'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'VPImageCropper'
pod 'KVNProgress'
pod 'RongCloudIMKit'
pod 'ActionSheetPicker-3.0'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengMessage'
pod 'JDFlipNumberView'
pod 'UMengSocial'
pod 'AliyunOSSiOS'
pod 'GTSDK'
